spring.application.name=cl
spring.datasource.url=jdbc:postgresql://localhost:5432/Fingeso
spring.datasource.username=postgres
spring.datasource.password=1360
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.port=8080
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
